ruby_version: ruby-2.2.0
bundler_version: 1.10.6
test_pattern:
  - spec/**/*_spec.rb
coverage:
  ratchet: 90
sqlite: true
rake:
  rails_env: 'test'
hooks:
  pre_setup: bundle exec rake solano:link_config_files
  worker: bundle exec rake db:drop db:schema:load
  post_build: bundle exec rake solano:post_build_hook
environment:                              # Environment variables to set when services & tests run
  RAILS_LOG_LEVEL: '0'                    # Default is 4; 0-3 are more verbose
